version: '3.7'
services:
  server:
    image: yakwilik/mrga_backend

    command: make run

    working_dir: '/project'
    volumes:
      - "${PWD}/:/project/"
    network_mode: "host"

  postgres:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: "mashadb"
      POSTGRES_USER: "mashapg"
      POSTGRES_PASSWORD: "mashapg"
    volumes:
      - ./sql_scripts/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

#networks:
#  service-network:
#    driver: bridge
