version: '3.7'
services:
  server:
    image: yakwilik/boost_1_81_beta

    command: bash -c "cd build && ./server"
    restart: always

    working_dir: '/project'
    networks:
      - service-network
    ports:
      - '8081:8080'

networks:
  service-network:
    driver: bridge