name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - run: make build
  test:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: make test
  memtest:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: make memtest
  covtest:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: make covtest
