name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    steps:
      - uses: actions/checkout@v2
      - run: make build
  build:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_all
    steps:
    - uses: actions/checkout@v2
    - run: make build
