on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    steps:
      - uses: actions/checkout@v2
      - run: make build
  clean:
    runs-on: ubuntu-latest
    container: bodjan/cxx
    steps:
    - uses: actions/checkout@v2
    - run: make clean