name: client

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_project:26102022_2
    steps:
      - uses: actions/checkout@v2
      - run: cd project/client/interface && make check
  build:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_project:26102022_2
    steps:
      - uses: actions/checkout@v2
      - run: cd project/client/interface && make build
  test:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_project:26102022_2
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: cd project/client/interface && make test
  memtest:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_project:26102022_2
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: cd project/client/interface && make memtest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Valgrind logs
          path: valgrind.log
  covtest:
    runs-on: ubuntu-latest
    container: yakwilik/cxx_project:26102022_2
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: |
            sudo pacman -S --noconfirm tree
            cd project/client/interface && tree build && make covtest
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Test coverage
          path: build/report/